apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: flux-applier-pvc
rules:
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flux-applier-pvc
subjects:
  - kind: ServiceAccount
    name: flux-applier
    namespace: jenkinssoanr
roleRef:
  kind: ClusterRole
  name: flux-applier-pvc
  apiGroup: rbac.authorization.k8s.io