apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonar
  namespace: jenkinssoanr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonar
  template:
    metadata:
      labels:
        app: sonar
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: sonar
          image: sonarqube:lts
          ports:
            - containerPort: 9000
          args:
            - "-Dsonar.web.context=/sonar"
          env:
            - name: SONAR_ES_BOOTSTRAP_CHECKS_DISABLE
              value: "true"
          resources:
            requests:
              memory: "1Gi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "500m"
          volumeMounts:
            - name: sonar-data
              mountPath: /opt/sonarqube/data
      volumes:
        - name: sonar-data
          persistentVolumeClaim:
            claimName: sonar-data-pvc