---
apiVersion: v1
kind: Service
metadata:
  name: sonar
  namespace: jenkinssoanr
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9000
      targetPort: 9000
  selector:
    app: sonar
