apiVersion: v1
kind: Service
metadata:
  name: sonar
  namespace: jenkinssoanr
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 9000
      targetPort: 9000
      nodePort: 30900
  selector:
    app: sonar