---
# Order Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: ecommerce
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: pipebarreto/order-service:stage
          ports:
            - containerPort: 8300
          envFrom:
            - configMapRef:
                name: ecommerce-config
          env:
            - name: EUREKA_INSTANCE_HOSTNAME
              value: "order-service"
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
