# favourite Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: favourite-service
  namespace: ecommerce
  labels:
    app: favourite-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: favourite-service
  template:
    metadata:
      labels:
        app: favourite-service
    spec:
      containers:
      - name: favourite-service
        image: pipebarreto/favourite-service:1.0.0-dev.9
        ports:
        - containerPort: 8800
        envFrom:
        - configMapRef:
            name: ecommerce-config
        env:
        - name: EUREKA_INSTANCE_HOSTNAME
          value: "favourite-service"
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"