---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkinssoanr
spec:
  replicas: 0
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      securityContext:
        runAsUser: 0
      containers:
        - name: jenkins
          image: pipebarreto/jenkinsk:lts
          ports:
            - containerPort: 8080
            - containerPort: 50000
          env:
            - name: JENKINS_OPTS
              value: "--prefix=/jenkins"
          resources:
            requests:
              memory: "1Gi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "500m"
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home
      volumes:
        - name: jenkins-home
          persistentVolumeClaim:
            claimName: jenkins-data-pvc
