# payment Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: ecommerce
  labels:
    app: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: pipebarreto/payment-service:stage
        ports:
        - containerPort: 8400
        envFrom:
        - configMapRef:
            name: ecommerce-config
        env:
        - name: EUREKA_INSTANCE_HOSTNAME
          value: "payment-service"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
