# Cloud Config Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-config
  namespace: ecommerce
  labels:
    app: cloud-config
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-config
  template:
    metadata:
      labels:
        app: cloud-config
    spec:
      containers:
      - name: cloud-config
        image: pipebarreto/cloud-config:latest
        ports:
        - containerPort: 9296
        envFrom:
        - configMapRef:
            name: ecommerce-config
        env:
        - name: SPRING_CONFIG_IMPORT
          value: ""
        - name: EUREKA_INSTANCE_HOSTNAME
          value: "cloud-config"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"