---
# shipping Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-service
  namespace: ecommerce
  labels:
    app: shipping-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipping-service
  template:
    metadata:
      labels:
        app: shipping-service
    spec:
      containers:
        - name: shipping-service
          image: pipebarreto/shipping-service:1.0.0-dev.10
          ports:
            - containerPort: 8600
          envFrom:
            - configMapRef:
                name: ecommerce-config
          env:
            - name: EUREKA_INSTANCE_HOSTNAME
              value: "shipping-service"
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
